before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y --force-yes
before_script:
  - rethinkdb --daemon
  - psql -c 'create database ger_test;' -U postgres
language: node_js
node_js:
  - "0.11"
after_script:
  - killall rethinkdb